### ISSUE TITLE
Fix missing spacing in "Sample Data" selection component

### ISSUE THREAD

**Issue by pverscha** [unipept/unipept-web-components#29]
There seems to be some spacing missing between the "Load Dataset" button and the dropdown in the `LoadDatasetsCard`.

This is what the card looks like in the web components:
![image](https://user-images.githubusercontent.com/9608686/66902077-50eebc00-f000-11e9-8fbc-c8046f849803.png)

And this is what it should look like (morty.ugent.be):
![image](https://user-images.githubusercontent.com/9608686/66902230-990dde80-f000-11e9-92d4-777cac451585.png)

The only changes between both applications is the upgrade to Vuetify 2.0 in the web components.

**Comment by bmesuere** [comment]
Not that it's a (major) problem, but the font is also different. The top screenshot seems to use something like Google's Product Sans

**Comment by pverscha** [comment]
Vuetify decided to switch fonts in version 2.0. I'll also increase the contrast of the font and the background, to improve readability.
